apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watchdog-kube-controller-manager
  namespace: openshift-kube-controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - pods
    verbs:
      - get
      - list
      - watch
      - create
