apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-controller-manager-config
  namespace: kube-system
  labels:
    tier: "control-plane"
    k8s-app: "kube-controller-manager"
    openshift.io/control-plane: "true"
    openshift.io/component: "controller"
data:
  config.yaml: |
    {{ .PostBootstrapKubeControllerManagerConfig | indent 4 }}
